### ISSUE TITLE
Hybrid state gxhash

### ISSUE THREAD

**Issue by ogxd** [ogxd/gxhash#34]
# Context

Currently, gxhash with a 128-bit state is much faster for small input sizes, while gxhash with a 256-bit state is faster for large input sizes. The idea is to study the possibilities of making an hybrid state version of gxhash, leveraring the advantages of 128-bit state with the advantages of the 256-bit state processing, for maximum throughput for all input sizes.

See the break-even point:
<img width="434" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/e035bbac-53e1-4853-a838-541ae74fde56">

# Challenges

There are two ways to achieve this:
- Either modify the 256-bit state version to use 128-bit state logic for small input sizes
- Or try to make the 256-bit state processing stable along the 128-bit state. This is more complex, but if achieved, it could greatly simplify the usage of gxhash as a whole (stable for intrinsics set width)

Some challenges are:
- It must be all evaluated at compile time because we don't want to increase the bytecode of the algorithm. There could not be a dynamic switch between two state width paths in the algorithm.
- Making 256-bit and 128-bit stable requires rethinking of the high ILP construction

# Todo

- [x] Study possibilities of using generics to avoid dynamic state width evaluation
- [x] Figure out where the break-even point is
- [x] Study the possibility of having a stable high ILP construction for both 128 and 256 bit states

**Comment by ogxd** [comment]
Results for first try at an hybrid approach
<img width="600" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/18cfa6da-5c98-49fa-a511-629fa8185033">

**Comment by ogxd** [comment]
<img width="622" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/6aa1c5b0-48d6-45c9-b897-cf824cd597f9">
<img width="622" alt="image" src="https://github.com/ogxd/gxhash/assets/12692438/3e11a5cf-8a43-4cb9-8b8e-b815567bebda">

**Comment by xxaier** [comment]
s128 s256 hybird and the other hash maybe can draw it in the same picture so it looks clearer

**Comment by ogxd** [comment]
Interesting but I doubt IA (at least IA as we know it currently) would help making gxhash more performant

**Comment by ogxd** [comment]
Yes all hashes generated in v3 will be the same, independently from actual intrinsics used.   
I did one more batch of optimizations yesterday but I am reaching the limits (or at least my limit 😅). 
I am going to proceed to a cleanup and review this as a whole
